# -*- coding: utf-8 -*-

from . import country
from . import currency
from . import lang
from . import amazon_marketplace
from . import amazon_seller
from . import amazon_shop
from . import product_template
from . import product_product
from . import product_image
from . import merchant_category
from . import copy_platform
from . import product_attribute
from . import product_attribute_value
from . import product_description
from . import product_brand
from . import freight_line
from . import freight_template
from . import product_category
from . import shop_template
from . import amazon_browse_node
from . import amazon_category
from . import ir_sequence
from . import upc_code
from . import submission_history
from . import sale_order
from . import sale_order_line
from . import sync_sale_order_log
from . import variation_theme
from . import res_users
from . import ir_cron
from . import stock_location
from . import stock_picking
from . import logistics_company
from . import purchase_order
