order = {
    'CreatedBefore': {'value': '2018-01-25T01:41:05Z'},
    'Orders': {
        'Order': {
            'PaymentMethodDetails': {'PaymentMethodDetail': {'value': 'Standard'}, 'value': '\n          '},
            'LatestDeliveryDate': {'value': '2018-03-09T07:59:59Z'},
            'LatestShipDate': {'value': '2018-01-27T07:59:59Z'},
            'EarliestShipDate': {'value': '2018-01-25T08:00:00Z'},
            'IsPremiumOrder': {'value': 'false'},
            'IsBusinessOrder': {'value': 'false'},
            'ShippedByAmazonTFM': {'value': 'false'},
            'PurchaseDate': {'value': '2018-01-24T02:14:56Z'},
            'ShipmentServiceLevelCategory': {'value': 'Standard'},
            'OrderTotal': {
                'CurrencyCode': {'value': 'USD'},
                'Amount': {'value': '20.50'},
                'value': '\n          '},
            'AmazonOrderId': {'value': '113-4418725-3029069'},
            'FulfillmentChannel': {'value': 'MFN'},
            'NumberOfItemsUnshipped': {'value': '0'},
            'OrderStatus': {'value': 'Shipped'},
            'IsReplacementOrder': {'value': 'false'},
            'ShippingAddress': {
                'City': {'value': 'FORT PAYNE'},
                'AddressType': {'value': 'Commercial'},
                'Name': {'value': 'Matt Whitfield'},
                'CountryCode': {'value': 'US'},
                'value': '\n          ',
                'Phone': {'value': '2566014834'},
                'StateOrRegion': {'value': 'AL'},
                'AddressLine1': {'value': '611 GODFREY AVE SE'},
                'PostalCode': {'value': '35967-1629'}},
            'OrderType': {'value': 'StandardOrder'},
            'LastUpdateDate': {'value': '2018-01-24T11:03:13Z'},
            'EarliestDeliveryDate': {'value': '2018-02-14T08:00:00Z'},
            'PaymentMethod': {'value': 'Other'},
            'SalesChannel': {'value': 'Amazon.com'},
            'BuyerEmail': {'value': '3vslppp6q85jl9r@marketplace.amazon.com'},
            'value': '\n        ',
            'ShipServiceLevel': {'value': 'Std US D2D Dom'},
            'BuyerName': {'value': 'Amanda Whitfield'},
            'NumberOfItemsShipped': {'value': '1'},
            'IsPrime': {'value': 'false'},
            'MarketplaceId': {'value': 'ATVPDKIKX0DER'}}, 'value': '\n      '},
    'value': '\n    '
}